### ISSUE TITLE
Add support for Android

### ISSUE THREAD

**Issue by nikgraf** [serenity-kit/react-native-libsodium#7]
Proposed approach: 

- remove all libsodium functions and get one `multiply` function working
- link the libsodium library and add back all libsodium functions

Resources: 

- https://ospfranco.com/post/2021/02/24/how-to-create-a-javascript-jsi-module/
- https://blog.notesnook.com/getting-started-react-native-jsi/
- https://ospfranco.notion.site/Android-ccdf0ebed2e94efbba2fb3dfb03154af

**Comment by arnaudambro** [comment]
hello !
I'm really glad you're doing this lib.
May I ask a few questions ? Because I'm a user of `react-native-sodium` for one of our project (https://github.com/SocialGouv/mano/blob/a9decd87fc47401d14639b9718204c348aa7bc49/app/src/services/encryption.js), and the `decrypt` function is quite slow...

1. what do you think will be the main difference between your lib and `react-native-sodium`?
2. do you plan to add Android anytime soon? no pressure 😄 just asking

Thanks a lot, and good luck!

**Comment by nikgraf** [comment]
Shipped Android support :)
